### ISSUE TITLE
macOS 10.15无法安装

### ISSUE THREAD

**Issue by dreamyworm** [nervouself/webp-angle#1]
macOS 10.15无法安装

**Comment by nervouself** [comment]
应该是不需安装的，我猜是遇到无法打开的问题
遇到提示未知开发者的问题，请前往 系统偏好设置-安全性与隐私-通用，点击仍要打开
或在终端输入 sudo spctl --master-disable 并进入 系统偏好设置-安全性与隐私-通用，选择任何来源

**Comment by nervouself** [comment]
@dreamyworm 不知这个是否能解决你的问题
