### ISSUE TITLE
压完后反而更大了

### ISSUE THREAD

**Issue by peerless2012** [nervouself/webp-angle#13]
120帧png共计16M，压成动态webp后有22M。。。

**Comment by nervouself** [comment]
调一下压缩质量呢。。底层用的是 webp 官方 lib 了，按理不应该

**Comment by peerless2012** [comment]
调到40后大小跟未处理之前的png序列帧一样大。。。

**Comment by nervouself** [comment]
你把源文件发出来我看看呢

**Comment by peerless2012** [comment]
[VAP pngs](https://github.com/Tencent/vap/tree/master/tool/simple_demo)

**Comment by peerless2012** [comment]
跟我一样吗？

**Comment by nervouself** [comment]
我试了下确实是，猜测应该是图片颜色太复杂了导致 webp 这个算法不太优了，可以先手动把 png 压一下再转，或者试下 apng
