### ISSUE TITLE
Windows程序所在路径中有空格会引发报错

### ISSUE THREAD

**Issue by ElementMo** [nervouself/webp-angle#15]
![QQ截图20211010223633](https://user-images.githubusercontent.com/27777504/136700339-be60b7bd-d864-4b0f-9a16-84ff7e3beef0.png)

**Comment by ElementMo** [comment]
以及，图片路径过长，超出cmd字符串限制长度8191个字符时也会引发报错
https://docs.microsoft.com/zh-cn/troubleshoot/windows-client/shell-experience/command-line-string-limitation
![image](https://user-images.githubusercontent.com/27777504/136700843-27303a94-3010-4812-9663-36ac67daa84b.png)

SHCreateStreamOnFile((const LPTSTR)filename, STGM_READ, stream) failed 80070002
Error opening input file E:\PR\ssssssssssssss\720p (80070002)
OpenInputStream(filename, &stream) failed 80070002
cannot open input file 'E:\PR\ssssssssssssss\720p'

**Comment by nervouself** [comment]
这个是 cmd 的一些问题，暂时还没好的解决方案，后面考虑内置个 shell，但是这个一时半会还搞不定
