### ISSUE TITLE
为啥我以前打开没事，现在打开屏幕是空？

### ISSUE THREAD

**Issue by SalivaRedmine** [nervouself/webp-angle#17]
打开之后，灰屏，也无法操作，是个空界面

**Comment by SalivaRedmine** [comment]
Win10

**Comment by SalivaRedmine** [comment]
![image](https://user-images.githubusercontent.com/65207214/155848227-7a2f45fc-bbbc-4ac3-b41a-6e930fb1160e.png)

**Comment by nervouself** [comment]
已经修复了，稍后请下载新的 1.6.1 版本
