### ISSUE TITLE
win平台无法使用

### ISSUE THREAD

**Issue by hooke007** [nervouself/webp-angle#3]
报错如图

<a href="https://sm.ms/image/euwKp4fDrRdWNJ3" target="_blank"><img src="https://i.loli.net/2020/09/04/euwKp4fDrRdWNJ3.jpg" /></a>

**Comment by nervouself** [comment]
我去研究下！抱歉！

**Comment by nervouself** [comment]
已解决，感谢反馈
新版[release](https://github.com/nervouself/webp-angle/releases/tag/v1.6.0)
