### ISSUE TITLE
都按照说的做了，显示webp 小天使无法打开

### ISSUE THREAD

**Issue by NickHu150** [nervouself/webp-angle#4]
隐私和sudo命令都用了

**Comment by nervouself** [comment]
经过排查，是 builder 工具在 mac 10.15 版本上的问题，稍等我手动打包上传一下，感谢反馈

**Comment by NickHu150** [comment]
> 经过排查，是 builder 工具在 mac 10.15 版本上的问题，稍等我手动打包上传一下，感谢反馈

非常感谢，另外我们是需要自定义一些动态webp的一些参数，比如每张图片独立显示，不与上一针合成，不知道是否支持

**Comment by nervouself** [comment]
> > 经过排查，是 builder 工具在 mac 10.15 版本上的问题，稍等我手动打包上传一下，感谢反馈
> 
> 非常感谢，另外我们是需要自定义一些动态webp的一些参数，比如每张图片独立显示，不与上一针合成，不知道是否支持

每帧之间可以没有关系，惟一限制就是动图每帧尺寸要相同

**Comment by nervouself** [comment]
新包已经上传，麻烦重新下载试用

**Comment by NickHu150** [comment]
> 新包已经上传，麻烦重新下载试用

可以留个联系方式么，这个工具使用上还有一些小问题，想跟您沟通一下

**Comment by NickHu150** [comment]
@nervouself 我们有些webp单张不是透明的，但是需要播放的时候每一张独立显示，用webp小天使之后会出现重叠，希望能否加一个在下一张显示的时候去除前一帧合成的功能，我看有些网站是支持这个功能的

**Comment by nervouself** [comment]
> @nervouself 我们有些webp单张不是透明的，但是需要播放的时候每一张独立显示，用webp小天使之后会出现重叠，希望能否加一个在下一张显示的时候去除前一帧合成的功能，我看有些网站是支持这个功能的

我自用各种情况也都试过，没出现重叠的情况。。可以提供下图片我稍后复现下吗

**Comment by yuntoxixi** [comment]
@nervouself 你好，mac版，下载之后，无法打开，如何解决呢？

**Comment by nervouself** [comment]
你好，我正在解决当中



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nervouself/webp-angle] 都按照说的做了，显示webp 小天使无法打开 (#4)





 
@nervouself 你好，mac版，下载之后，无法打开，如何解决呢？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nervouself** [comment]
> @nervouself 你好，mac版，下载之后，无法打开，如何解决呢？

请下载 1.6.2 版本

**Comment by yuntoxixi** [comment]
完美解决，非常感谢！谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nervouself/webp-angle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nervouself/webp-angle] 都按照说的做了，显示webp 小天使无法打开 (#4)





  
@nervouself 你好，mac版，下载之后，无法打开，如何解决呢？
  
请下载 1.6.2 版本
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
